#### 异常继承体系

![](https://img-blog.csdnimg.cn/2019102821180396.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2pvaG5XY2hldW5n,size_16,color_FFFFFF,t_70)

1. Exception：Exception是程序正常运行中，可以预料的意外情况，可能并且应该被捕获，进行相应处理。

   1. 检查型异常（在源代码里必须显式地进行捕获处理）

      1. IOException
      2. SQLException
      3. ClassNotFoundException
      4. InterruptedException


   1. 运行时异常：RuntimeException。通常是可以编码避免的逻辑错误，具体根据需要来判断是否需要捕获，并不会在编译期强制要求

      1. NullPointerException


      2. ArithmeticException


      3. ClassCastException


      4. IndexOutOfBoundsException


      5. NumberFormatException

         ​

1. Error：在正常情况下，不大可能出现的情况，绝大部分的Error都会导致程序（比如JVM自身）处于非正常的、不可恢复状态。既然是非正常情况，所以不便于也不需要捕获

   1. OutOfMemoryError 内存溢出错误
   2. StackOverflowError 栈内存溢出错误
   3. NoClassDefFoundError 找不到class定义的错误

2. 自定义异常

   1. 所有异常都必须是 Throwable 的子类。
   2. 如果希望写一个检查性异常类，则需要继承 Exception 类。
   3. 如果你想写一个运行时异常类，那么需要继承 RuntimeException 类。

3. try-catch-finally

   程序员的惯性认知：当遇到return语句的时候，执行函数会立刻返回。但是，在Java语言中，如果存在finally就会有例外。除了return语句，try代码块中的break或continue语句也可能使控制权进入finally代码块。

   ​